/* Dice Duel · as falas aprovadas do modo história (gerado por tools/historia/piadas_fonte.py; não editar) */
window.HISTORIA_FALAS = {
"P-01": "Boa noite. Você joga dados?",
"P-02": "Não importa. Eu ensino. Sou ótima professora e péssima em deixar coisas em cima da mesa.",
"P-03": "Não pergunte do nariz.",
"P-04": "Você aprende rápido.",
"P-05": "Ótimo. Preciso de um favor. Alguém levou sete páginas do meu caderno de receitas.",
"P-06": "Sete. Como a soma dos opostos. Não é coincidência. Quase nada é.",
"G-01": "Eco. O mesmo número. Gêmeos idênticos: mesmo código, opiniões diferentes.",
"G-02": "Passo. Um a mais ou um a menos. Uma mutação pequena. A maioria passa despercebida. (toca no nariz) A minha, não.",
"G-03b": "Oposto. Somam sete: um e seis, dois e cinco, três e quatro. Cada número tem o seu par. Quase romântico.",
"G-04": "Três elos. Um códon: a menor frase que a vida sabe ler. Já dá para disparar.",
"G-05": "Rompeu. Na natureza chamam isso de mutação. Aqui chamamos de \"arrisquei demais\".",
"G-06": "O Bolso guarda um dado. A vida guarda duas fitas pelo mesmo motivo.",
"C1-01": "Dobrei a dose.",
"C1-02": "O Sapo está com a página um. Ele é educado. Vai te oferecer chá. / Não aceite. É água do lago.",
"C1-03": "Boa noite. Aceita um chá?",
"C1-04": "É do lago, sim. Orgânico.",
"C1-05": "A página se chama \"Sopa de Girino ao Contrário\". Achei de mau gosto. Já fui girino.",
"C1-06": "Ganhe e ela é sua. Perca, e você toma o chá.",
"C1-07": "Calma. Aqui o tempo anda devagar.",
"C1-08": "Reverso: a fita volta pela outra ponta. Já fui girino. Não volto nem com transcriptase.",
"C1-09": "Que salto.",
"C1-10": "Escorreguei na vitória-régia.",
"C1-11": "Chá?",
"C1-12": "Justo. A página é sua. O chá também, se quiser.",
"C1-13a": "SOPA DE GIRINO AO CONTRÁRIO · Ingredientes: A, T, C e G. Nessa ordem. Ou na outra.",
"C1-13b": "(margem, na letra da Diana) Ler no espelho. Ou com o Reverso.",
"C1-14": "Sabe por que ela quer isso? Dizem que a salamandra regenera uma perna inteira. / Eu não. Sou sapo. Todo mundo confunde.",
"I1-01": "Uma a menos.",
"I1-02": "O que é o DNA, se não um conjunto de dados?",
"I1-03": "…Coisa de receita. Próximo: o Coelho.",
"C2-01": "O Coelho tem a página dois. Ele joga rápido.",
"C2-02": "Ele faz tudo rápido. A família dele que o diga: são quarenta e três.",
"C2-03": "Desculpe, estou atrasado. Para tudo. Sempre.",
"C2-04": "A página? \"Pão que Cresce Sozinho\". Testei. Cresceu. Tivemos que mudar de toca.",
"C2-05": "Jogo rápido, tá? Tenho reunião de família. É uma reunião grande.",
"C2-06": "Valendo. Vai. Vai. Vai.",
"C2-07": "Mais dois. Aqui em casa mais nunca é demais. É só… mais.",
"C2-08": "Isso conta como multiplicação?",
"C2-09": "Contei errado. De novo. Eram quarenta e quatro.",
"C2-10": "Ganhei! Preciso ir. Atrasado.",
"C2-11": "Toma a página. Corre que ainda dá tempo de… alguma coisa.",
"C2-12a": "PÃO QUE CRESCE SOZINHO · Ingredientes: G, G, G e G. Fermento: sim.",
"C2-12b": "(margem, na letra da Diana) Não deixar o Coelho ler.",
"C2-13": "Ela é sua amiga? Avisa que o curativo está torto.",
"C2-14a": "Ela tem outras receitas? Pergunto por um amigo. Quarenta e três amigos.",
"C3-01": "Inspiração.",
"C3-02": "A Raposa tem a página três. Ela vai mentir para você. / Não. Pior. Ela vai dizer a verdade de um jeito que parece mentira.",
"C3-03": "E ela usa armadilhas. Eu também. Achei que era hora de contar.",
"C3-04a": "Ah. Você deve ser o projeto da gata.",
"C3-05": "No inverno eu fico branca, sabia? É genética. O cachecol é escolha.",
"C3-06": "A página é \"Torta de Fundo Falso\". Adorei. Quase não devolvo. / … / Quase.",
"C3-07": "Fique à vontade. Nada aqui é o que parece. Inclusive eu.",
"C3-08": "Armei alguma coisa. Ou não. É uma raposa falando.",
"C3-09": "O fundo era falso. A raposa, verdadeira.",
"C3-10": "Hm. Você não é fácil de enganar.",
"C3-11": "Que deselegante. Para mim.",
"C3-12": "Volte quando quiser perder com estilo.",
"C3-13": "Leve. E cuidado com a gata: ela é mais raposa do que eu.",
"C3-14a": "TORTA DE FUNDO FALSO · Recheio: segredo. Até para quem come.",
"C3-14b": "(debaixo de uma aba da página) Achou que ia ter receita aqui?",
"C4-01": "É um acessório. / … / Está na moda. Em clínica veterinária.",
"C4-02": "O Urso tem a página quatro. Está hibernando. Não acorde ele. / Quer dizer: acorde. Com educação.",
"C4-03": "…É primavera?",
"C4-04b": "Não? Então me acorda em março.",
"C4-05": "CAIXA: Ursos hibernam meses e acordam sem perder músculo. A ciência quer muito esse segredo. / URSO: O segredo é não acordar.",
"C4-06": "(bocejo) Vai você primeiro. Vai você sempre.",
"C4-07": "Pausa. Não é preguiça. É estratégia de inverno.",
"C4-08": "Hm. Isso foi… acordado.",
"C4-09": "Cochilei no meio.",
"C4-10": "Pronto. Posso voltar a dormir?",
"C4-11": "Leva a página. Fecha a porta. Apaga a luz.",
"C4-12a": "MEL EM BANHO-MARIA · Tempo de preparo: um inverno.",
"C4-12b": "(margem, na letra da Diana) Não acordar o mel.",
"C4-13": "(dormindo) …a gata… o nariz… ela pediu pra não contar… / (ronco)",
"C5-01": "O cone sumiu. / Suspeito de alguém de máscara.",
"C5-02": "Por coincidência, o Guaxinim tem a página cinco. Por coincidência, ele usa máscara. Eu não acredito em coincidência.",
"C5-03": "Isso? Achei.",
"C5-04": "Não roubei. Fiz uma transferência horizontal.",
"C5-05": "Bactéria faz isso o tempo todo: pega o gene do vizinho e pronto. Ninguém prende bactéria.",
"C5-06": "As páginas? Fui eu, sim. Todas. Depois vendi uma para cada bicho. / Modelo de assinatura.",
"C5-07": "Bonito seu Bolso. Seria uma pena se…",
"C5-08": "Troca justa. Para mim.",
"C5-09": "Taxa de serviço.",
"C5-10": "Ei. Isso era meu. Quer dizer. Ia ser.",
"C5-11": "Lixo. Literalmente.",
"C5-12": "Volte sempre. Traga coisas.",
"C5-13": "Tá. Leva a página. E o cone. / …Fica com o cone? Não? Tá.",
"C5-14a": "SALADA DE SOBRAS DOS OUTROS · Ingredientes: os do vizinho.",
"C5-14b": "(etiqueta de preço colada na página) Página 5 · 4,99 por mês",
"C5-15": "Pergunta pra gata quem deixou a janela aberta.",
"C6-01": "Algodão. / … / É lã. Da Ovelha. Ela ainda não sabe.",
"C6-02": "Página seis. Ela é simpática. Não fale de clonagem.",
"C6-03": "Não sou a Dolly.",
"C6-04": "Não sou parente da Dolly. Não lembro dela. Sim, todo mundo pergunta.",
"C6-05": "Quer trocar? Dou duas pedras por um dado. / … / Ninguém nunca quer a ovelha. Eu sei.",
"C6-06": "Rola. Vê se sai sete.",
"C6-07": "Espelho: uma cópia de você, ao contrário. É o mais perto de clone que eu chego.",
"C6-08": "Bééém jogado.",
"C6-09": "Desmanchou. Igual tricô.",
"C6-10": "Leva um pouco de lã de lembrança. Parece que alguém já levou.",
"C6-11": "Toma a página. E diz pra gata devolver a minha lã.",
"C6-12a": "PUDIM GÊMEO · Rende: duas porções idênticas. A segunda não lembra da primeira.",
"C6-12b": "(margem, na letra da Diana) Uma delas é a cópia. Não pergunte qual.",
"I6-01": "Cansei de disfarçar.",
"I6-02": "Não é nada. É um lençol.",
"I6-03": "Última página. Dona Coruja. Ela sabe ler. / Ler a Mesa. Ler gente. Ler… coisas que eu não contei.",
"C7-01": "Boa noite. Sente-se. A Diana mandou você.",
"C7-02": "Mandou você em todo mundo antes de mim. Esperta. Mandou você treinar.",
"C7-03": "Ela vai te dizer que \"Dona Coruja\" também começa com D. Diga a ela que \"Dona\" é pronome de tratamento.",
"C7-04": "Sem pressa. Quem escreve precisa saber ler.",
"C7-05": "Lacre. Nem tudo que está escrito precisa ser dito.",
"C7-06": "Jogada precisa. Você leu.",
"C7-07": "Hum. Escrevi uma letra errada. Acontece com os melhores.",
"C7-08": "Ainda não. Volte quando ler mais rápido.",
"C7-09": "Agora sim. Sente-se. Precisamos falar da gata.",
"C7-10b": "(quadro mudo: ela só entrega a página)",
"C7-11": "Uma letra errada, no meio de quase três bilhões. Um Passo onde devia haver um Eco. Por isso não fecha.",
"C7-12": "Ela não te ensinou a jogar por gentileza. Pergunte a ela.",
"R-01": "Você acha que é coincidência tudo começar com D?",
"R-02": "Meu nome. Dados. DNA. Está tudo conectado.",
"R-03": "Até a Dona Coruja. / Ela diz que \"Dona\" é pronome de tratamento. / É o que um D diria.",
"R-04": "Uma letra. Errada. Desde que eu nasci. O corte foi a quina de um dado. O não fechar é comigo.",
"R-05": "Eu tentei sozinha. Mas com essas patas fica difícil.",
"R-06": "Então eu ensinei alguém que monta correntes melhor do que eu. / … / Você.",
"R-07": "Usei. Ensinei. Em gatês é a mesma palavra.",
"R-08": "O Guaxinim levou. Eu deixei a janela aberta. Com um bilhete: \"por favor, não leve as páginas\". / Guaxinim não lê bilhete. Eu sabia.",
"R-10": "COELHO: Então… não é um livro de receitas? / DIANA: É. / A receita sou eu.",
"R-11": "Falta escrever. A correção tem que ser feita contra a fita original. A fita original sou eu. / Jogue sério. Se eu facilitar, a cura sai com defeito.",
"C8-01": "Boa noite. Uma partida? / (balão menor) Dessa vez vale.",
"C8-02": "Par complementar. A com T. Bonito.",
"C8-03": "Espelho. Você vai ter que ler ao contrário. Como eu.",
"C8-04": "Isso. Escreve assim.",
"C8-05": "Arrisquei demais. De novo. Está no meu DNA.",
"C8-06": "Ainda não. Revanche? / Por favor.",
"C8-07": "Mereceu.",
"F-01": "Dois, cinco, dois, cinco. / …Parece senha de wi-fi.",
"F-02": "O três e o quatro não dizem nada. São tipo \"hmm\". Todo texto tem.",
"F-03b": "Faz cócegas. / Cócegas.",
"F-A": "Fechou. Fechou. / Por que eu estou falando duas vezes? Vezes? / Você pôs um Eco. Eco. / …Passa amanhã. Manhã. / Revanche? Vanche?",
"F-A2": "Fita complementar perfeita. Eu ensinei bem. Bem.",
"C1-16": "Ah: se vir uma raposa de cachecol com um dado verde, / o dado é meu.",
"C2-15": "Dado branco, clássico. Eu não escolhi: / com quarenta e três filhos, o dado é o que sobra.",
"C2-16": "Um, um, dois, três, cinco… / Isso não é corrente. É a minha família.",
"C3-17": "A Raposa está com um dado verde novo. O Sapo está procurando o dele. / Não é coincidência. Quase nada é.",
"C3-15": "O dado verde? Combina com o cachecol. / O Sapo chama isso de roubo. Eu chamo de mimetismo.",
"C4-14": "Mel não estraga, sabia? Acharam mel de três mil anos ainda bom. / Eu pretendo durar igual. Dormindo.",
"C6-15": "Cuidado comigo. Tenho cavalaria: três cavaleiros e o maior exército do pasto.",
"C6-16": "Somou sete: hora de mexer no ladrão. / …O Guaxinim acabou de passar.",
"F-Zb": "Eu te ensinei a jogar para me curar. / Agora jogue só porque é bom. / …E porque eu ainda quero a revanche.",
"C7-15a": "Um conselho de quem lê. Ela joga com as faces do avesso. / Leve um Lacre. Nem toda página precisa ser virada.",
"C7-15b": "Na célula, umas proteínas sentam em cima de um trecho do DNA, e ele não é lido. Chama-se silenciar um gene. / O Lacre faz isso com uma carta dela. Está na Loja.",
"C8-09a": "No Prólogo, quem começou com um dado no Bolso fui eu. / Você nem reparou. / Hoje também.",
"C8-09b": "Toda fita tem uma cópia de reserva: a outra fita. É com ela que a célula conserta os erros. / O meu Bolso é a minha. Começo com um dado.",
"X-01": "DianaDice não seria um nome melhor para esse jogo? / … / Seria.",
"X-02a": "SAPO: Soube da cura. Trouxe chá. / DIANA: É do lago? / SAPO: Orgânico."
};
window.HISTORIA_CENAS = {
"P-01": "A Diana atrás da mesinha de feltro. No nariz, um curativo com estampa de pips de dado.",
"P-02": "A pata dela empurra um dado devagar até a beirada.",
"P-03": "O dado cai para fora do quadro. Ela não olha.",
"P-04": "Ela olhando o placar.",
"P-05": "Um caderno \"RECEITAS DA DIANA\" com tocos de páginas arrancadas.",
"P-06": "Close no rosto dela.",
"C1-01": "Dois curativos cruzados em X no nariz.",
"C1-03": "O Sapo numa vitória-régia, tirando o chapéu de palha.",
"C1-04": "Uma xícara turva, com um girino dentro.",
"C1-13a": "A página molhada.",
"C1-13b": "A página molhada, com o título escrito espelhado: SOPA DE GIRINO AO CONTRÁRIO.",
"I1-01": "Ela lê a página um. No fundo, pela primeira vez, um mural de cortiça com uma foto de dado e um barbante vermelho.",
"I1-02": "Ela olha para o nada.",
"I1-03": "Ela percebe você olhando o mural e cobre a cortiça com a pata.",
"C2-01": "Curativo e, por cima, um adesivo: \"NÃO PERGUNTE\".",
"C2-03": "O Coelho com uma planilha, cercado de silhuetas de coelhinhos.",
"C2-12a": "Um pão saindo da fôrma e do quadro.",
"C2-12b": "A página com o título PÃO QUE CRESCE SOZINHO e uma mancha de farinha em forma de pata de coelho.",
"C3-01": "Um mini cachecol verde enrolado no nariz.",
"C3-03": "A Diana vira uma carta para baixo: o \"?\".",
"C3-04a": "A Raposa num sofá de toca, olhos semicerrados, satisfeita.",
"C3-14a": "Uma torta inteira, sem corte.",
"C3-14b": "A página TORTA DE FUNDO FALSO tem uma aba de papel colada; levantada, mostra só a frase.",
"C4-01": "A Diana com um cone de veterinário no pescoço.",
"C4-02": "O mural no fundo: três fotos e um bilhete \"DISPARO. DUELO. DOBRO. → D\".",
"C4-03": "Caverna escura, um volume enorme de gorro vermelho; o ronco desenhado com pips. Um olho abre.",
"C4-12a": "Um pote de mel de gorro, dormindo em banho-maria.",
"C4-12b": "A página MEL EM BANHO-MARIA, com o pote de mel desenhado de olhos fechados.",
"C4-13": "O Urso dormindo de novo; você puxa a página da pata dele.",
"C5-01": "Uma meia enrolada no nariz.",
"C5-03": "O Guaxinim num monte de tralha, usando o cone da Diana como abajur.",
"C5-14a": "Uma tigela com folhas de várias hortas.",
"C5-14b": "A página SALADA DE SOBRAS DOS OUTROS com uma etiqueta de preço por cima do título.",
"C6-01": "Um tufo branco e fofo no nariz.",
"C6-03": "A Ovelha num pasto de hexágonos, com uma falha na lã do ombro.",
"C6-12a": "Dois pudins iguais.",
"C6-12b": "Duas páginas PUDIM GÊMEO idênticas, grampeadas.",
"I6-01": "A Diana sem nada no nariz: o ferimento à mostra. Primeiro quadro sério da história.",
"I6-02": "O mural coberto por um lençol, o barbante vermelho saindo por baixo.",
"C7-01": "Biblioteca de estantes altas. Lombadas: \"Volume A\", \"Volume T\", \"Volume C\", \"Volume G\".",
"C7-03": "O Coelho numa mesa de leitura, ofegante, com uma pilha de livros de receitas e um pão que não cabe na mesa.",
"C7-09": "Reescrita sem gênero (era \"Está pronta\").",
"C7-10b": "Ela entrega a última página: só o desenho de um nariz de gato com um X.",
"C7-12": "Reescrita sem gênero (tirei o \"querida\").",
"R-01": "Ela puxa o lençol: o mural inteiro, barbante vermelho, a foto de cada bicho carimbada, a sua no meio, uma dupla hélice com dados no lugar dos degraus.",
"R-02": "Três cartões ligados pelo barbante: DIANA · DADOS · DNA.",
"R-03": "A foto da Coruja com um post-it \"D?\".",
"R-04": "Ela sentada, séria.",
"R-05": "A pata dela segurando uma pipeta, torta, pingando.",
"R-10": "O Coelho na porta, abraçado a um pão do tamanho dele.",
"R-11": "Ela na Mesa dela, os dados prontos.",
"C8-01": "A primeira fala do jogo, palavra por palavra.",
"C8-07": "Sem o \"Revanche?\" de sempre: vem a cena da cura.",
"F-01": "A sua corrente vencedora vira uma fita impressa com as letras embaixo: 2 5 2 5 → C G C G.",
"F-03b": "O ferimento fechado; ela encosta a pata. Antes, um quadro mudo. (Com esta, o \"Fechou.\" sai daqui e fica só no \"Fechou. Fechou.\" do fecho, e o eco começa já no \"Cócegas.\")",
"C1-16": "O Sapo apontando para fora do quadro, sério.",
"C2-15": "O Coelho com um dado branco gasto na pata, cercado de coelhinhos com dados coloridos.",
"C2-16": "Ciência: a sequência de Fibonacci nasceu de um problema sobre quantos coelhos nascem a cada mês (Liber Abaci, 1202).",
"C3-17": "O mural no fundo: a foto do Sapo e a da Raposa ligadas por um barbante, com um dado verde desenhado no meio.",
"C3-15": "A Raposa encostando o dado verde no cachecol verde: mesma cor. Ciência: mimetismo é quando um bicho imita a aparência de outro (ou do ambiente) para levar vantagem.",
"C4-14": "O Urso abraçado a um pote de mel, já fechando os olhos. Ciência: mel tem pouca água e é ácido; potes de milhares de anos foram achados comestíveis.",
"C6-15": "Homenagem aos jogos de tabuleiro de hexágonos (os cavaleiros e o maior exército), sem nome de jogo.",
"C6-16": "Homenagem: num jogo de hexágonos, o 7 move o ladrão; no Dice Duel, o 7 é o Oposto. Ciência: com dois dados, o sete é a soma mais provável (6 em 36).",
"F-Zb": "A Diana empurrando os dados de volta para o seu lado da mesa.",
"C7-15a": "A Dona Coruja batendo com a asa num lacre de cera vermelho em cima de um livro fechado.",
"C7-15b": "A Dona Coruja sentada em cima de um livro aberto, tampando a página. Ciência: proteínas repressoras se prendem ao DNA e impedem que um gene seja lido (transcrito).",
"C8-09a": "A Diana abre a pata: um dado rosa no Bolso dela. É verdade: no Prólogo, sem cartas, quem joga em segundo começa com um dado no Bolso, e quem jogava em segundo era ela.",
"C8-09b": "A Diana com um dado rosa no Bolso, a fita dupla do mural atrás dela. Ciência: no reparo do DNA, a célula usa a fita complementar como molde para refazer o trecho estragado.",
"X-01": "Ela risca \"Dice Duel\" com um pincel atômico e escreve por cima: \"DianaDice\".",
"X-02a": "A Diana, curada, abre a porta. O Sapo de chapéu, com uma xícara turva."
};
