'use strict';
const $=s=>document.querySelector(s),modalWrap=$('#modalWrap'),modal=$('#modal'),nodesEl=$('#nodes'),ghostEl=$('#ghost'),loopsEl=$('#loops'),edgesEl=$('#edges'),junctionsEl=$('#junctions'),pulsesEl=$('#pulses'),fxEl=$('#fx'),hint=$('#hint'),scoreEl=$('#scoreEl');
const STORAGE='knot-atlas-v8';let profile=JSON.parse(localStorage.getItem(STORAGE)||'{"maps":{}}');
function save(){localStorage.setItem(STORAGE,JSON.stringify(profile))}
function regular(n,rot=0,r=360){return Array.from({length:n},(_,i)=>{const a=i*Math.PI*2/n-Math.PI/2+rot;return[500+Math.cos(a)*r,500+Math.sin(a)*r]})}
function doubleSquare(rot=0){const p=[];for(let i=0;i<4;i++){let a=i*Math.PI/2-Math.PI/2+rot;p.push([500+Math.cos(a)*350,500+Math.sin(a)*350])}for(let i=0;i<4;i++){let a=i*Math.PI/2-Math.PI/4+rot;p.push([500+Math.cos(a)*205,500+Math.sin(a)*205])}return p}
const MAPS=[
{id:'first',feat:{label:'Trama híbrida · 2.200 pts + 2 Crosses',check:s=>s.score>=2200&&s.crosses>=2},name:'Primeira trama',desc:'Aprenda a fechar formas. Aqui a pontuação ainda é o objetivo.',moves:8,pts:regular(8),cross:140,echo:90,area:1,goals:[{label:'Passar · 1.400 pontos',check:s=>s.score>=1400,progress:s=>`${Math.min(1400,Math.round(s.score))}/1.400`},{label:'Prata · 2.200 pontos',check:s=>s.score>=2200,progress:s=>`${Math.min(2200,Math.round(s.score))}/2.200`},{label:'Ouro · 3.000 pontos',check:s=>s.score>=3000,progress:s=>`${Math.min(3000,Math.round(s.score))}/3.000`}]},
{id:'cross',feat:{label:'Caos controlado · 8 Crosses + 1 Loop',check:s=>s.crosses>=8&&s.loops>=1},name:'Cruzamento',desc:'Pontuação é secundária. O mapa existe para você aprender a fabricar Crosses.',moves:9,pts:regular(8,Math.PI/8),cross:180,echo:90,area:1,goals:[{label:'Passar · 4 Crosses',check:s=>s.crosses>=4,progress:s=>`${Math.min(4,s.crosses)}/4 Crosses`},{label:'Prata · 8 Crosses',check:s=>s.crosses>=8,progress:s=>`${Math.min(8,s.crosses)}/8 Crosses`},{label:'Ouro · 12 Crosses',check:s=>s.crosses>=12,progress:s=>`${Math.min(12,s.crosses)}/12 Crosses`}]},
{id:'echo',feat:{label:'Cadência fechada · 4 Echoes + 1 Loop',check:s=>s.echoes>=4&&s.loops>=1},name:'Jardim de Echo',desc:'Repita comprimentos consecutivos. Um mapa de ritmo e leitura espacial.',moves:9,pts:regular(8),cross:140,echo:150,area:1,goals:[{label:'Passar · 2 Echoes',check:s=>s.echoes>=2,progress:s=>`${Math.min(2,s.echoes)}/2 Echoes`},{label:'Prata · 3 Echoes',check:s=>s.echoes>=3,progress:s=>`${Math.min(3,s.echoes)}/3 Echoes`},{label:'Ouro · 4 Echoes',check:s=>s.echoes>=4,progress:s=>`${Math.min(4,s.echoes)}/4 Echoes`}]},
{id:'halo',feat:{label:'Halo tensionado · 2 Halos + 2 Crosses',check:s=>s.centerLoops>=2&&s.crosses>=2},name:'Halo',desc:'Feche formas que contenham o centro do mapa.',moves:9,pts:doubleSquare(),cross:140,echo:90,area:1,goals:[{label:'Passar · 1 Halo',check:s=>s.centerLoops>=1,progress:s=>`${Math.min(1,s.centerLoops)}/1 Halo`},{label:'Prata · 2 Halos',check:s=>s.centerLoops>=2,progress:s=>`${Math.min(2,s.centerLoops)}/2 Halos`},{label:'Ouro · 3 Halos',check:s=>s.centerLoops>=3,progress:s=>`${Math.min(3,s.centerLoops)}/3 Halos`}]},
{id:'star',feat:{label:'Constelação · Loop 8+ + 2 Echoes',check:s=>s.maxVertices>=8&&s.echoes>=2},name:'Estrela aberta',desc:'Construa um único Loop grande antes de gastar seu fio.',moves:11,pts:regular(10,Math.PI/10),cross:140,echo:90,area:1.12,goals:[{label:'Passar · Loop de 6 vértices',check:s=>s.maxVertices>=6,progress:s=>`Maior ${s.maxVertices}/6`},{label:'Prata · Loop de 8 vértices',check:s=>s.maxVertices>=8,progress:s=>`Maior ${s.maxVertices}/8`},{label:'Ouro · Loop de 10 vértices',check:s=>s.maxVertices>=10,progress:s=>`Maior ${s.maxVertices}/10`}]},
{id:'twin',feat:{label:'Trama dupla · 4 Loops + 3 Crosses',check:s=>s.loops>=4&&s.crosses>=3},name:'Dupla trama',desc:'O desafio não é um Loop enorme, mas fechar vários sem desperdiçar arestas.',moves:10,pts:doubleSquare(Math.PI/4),cross:140,echo:90,area:1,goals:[{label:'Passar · 3 Loops',check:s=>s.loops>=3,progress:s=>`${Math.min(3,s.loops)}/3 Loops`},{label:'Prata · 4 Loops',check:s=>s.loops>=4,progress:s=>`${Math.min(4,s.loops)}/4 Loops`},{label:'Ouro · 5 Loops',check:s=>s.loops>=5,progress:s=>`${Math.min(5,s.loops)}/5 Loops`}]},
{id:'clean',feat:{label:'Pureza sob pressão · 2 limpos + 2.000 pts',check:s=>s.cleanLoops>=2&&s.score>=2000},name:'Linha limpa',desc:'Feche formas sem cruzar as arestas que fazem parte delas.',moves:9,pts:regular(8,Math.PI/8),cross:100,echo:90,area:1,goals:[{label:'Passar · 1 Loop limpo',check:s=>s.cleanLoops>=1,progress:s=>`${Math.min(1,s.cleanLoops)}/1 limpo`},{label:'Prata · 2 Loops limpos',check:s=>s.cleanLoops>=2,progress:s=>`${Math.min(2,s.cleanLoops)}/2 limpos`},{label:'Ouro · 3 Loops limpos',check:s=>s.cleanLoops>=3,progress:s=>`${Math.min(3,s.cleanLoops)}/3 limpos`}]},
{id:'master',feat:{label:'Polímata · 12 Crosses + 4 Loops + 2 Echoes',check:s=>s.crosses>=12&&s.loops>=4&&s.echoes>=2},name:'Trama mestra',desc:'Misture volume de Crosses com múltiplos Loops. Aqui não existe uma única resposta.',moves:12,pts:regular(10),cross:160,echo:100,area:1.08,goals:[{label:'Passar · 6 Crosses + 2 Loops',check:s=>s.crosses>=6&&s.loops>=2,progress:s=>`${Math.min(6,s.crosses)}/6 X · ${Math.min(2,s.loops)}/2 L`},{label:'Prata · 12 Crosses + 4 Loops',check:s=>s.crosses>=12&&s.loops>=4,progress:s=>`${Math.min(12,s.crosses)}/12 X · ${Math.min(4,s.loops)}/4 L`},{label:'Ouro · 18 Crosses + 5 Loops',check:s=>s.crosses>=18&&s.loops>=5,progress:s=>`${Math.min(18,s.crosses)}/18 X · ${Math.min(5,s.loops)}/5 L`}]},
{id:'mirror',feat:{label:'Reflexo fechado · 4 pares + 1 Loop',check:s=>s.symPairs>=4&&s.loops>=1},name:'Espelho',desc:'Construa pares de arestas refletidas no eixo vertical. A forma precisa conversar consigo mesma.',moves:10,pts:regular(8),cross:130,echo:90,area:1,goals:[{label:'Passar · 2 pares espelhados',check:s=>s.symPairs>=2,progress:s=>`${Math.min(2,s.symPairs)}/2 pares`},{label:'Prata · 3 pares espelhados',check:s=>s.symPairs>=3,progress:s=>`${Math.min(3,s.symPairs)}/3 pares`},{label:'Ouro · 4 pares espelhados',check:s=>s.symPairs>=4,progress:s=>`${Math.min(4,s.symPairs)}/4 pares`}]},
{id:'mosaic',feat:{label:'Mosaico tenso · 4 triângulos + 6 Crosses',check:s=>s.triangleLoops>=4&&s.crosses>=6},name:'Mosaico',desc:'Triângulos são pequenos, rápidos e fáceis de desperdiçar. Aprenda a encaixá-los.',moves:11,pts:regular(8,Math.PI/8),cross:120,echo:90,area:1,goals:[{label:'Passar · 2 triângulos',check:s=>s.triangleLoops>=2,progress:s=>`${Math.min(2,s.triangleLoops)}/2 triângulos`},{label:'Prata · 3 triângulos',check:s=>s.triangleLoops>=3,progress:s=>`${Math.min(3,s.triangleLoops)}/3 triângulos`},{label:'Ouro · 4 triângulos',check:s=>s.triangleLoops>=4,progress:s=>`${Math.min(4,s.triangleLoops)}/4 triângulos`}]},
{id:'ritual',feat:{label:'Ritual carregado · 2 sequências + 10 Crosses',check:s=>s.rituals>=2&&s.crosses>=10},name:'Ritual',desc:'Faça Cross → Echo → Loop em três jogadas distintas. Aqui o valor está na preparação da sequência.',moves:12,pts:regular(10),cross:150,echo:120,area:1,goals:[{label:'Passar · 1 sequência completa',check:s=>s.rituals>=1,progress:s=>`${Math.min(1,s.rituals)}/1 ritual`},{label:'Prata · 2 sequências completas',check:s=>s.rituals>=2,progress:s=>`${Math.min(2,s.rituals)}/2 rituais`},{label:'Ouro · 2 rituais + 4 Loops',check:s=>s.rituals>=2&&s.loops>=4,progress:s=>`${Math.min(2,s.rituals)}/2 R · ${Math.min(4,s.loops)}/4 L`}]},
{id:'focus',feat:{label:'Agulha · 5 Loops usando no máximo 5 pontos',check:s=>s.loops>=5&&s.uniqueVertices<=5},name:'Concentração',desc:'Faça mais com menos: muitos Loops usando poucos pontos diferentes.',moves:10,pts:regular(8),cross:130,echo:90,area:1,goals:[{label:'Passar · 2 Loops usando ≤6 pontos',check:s=>s.loops>=2&&s.uniqueVertices<=6,progress:s=>`${Math.min(2,s.loops)}/2 L · ${s.uniqueVertices}/6 pts`},{label:'Prata · 3 Loops usando ≤6 pontos',check:s=>s.loops>=3&&s.uniqueVertices<=6,progress:s=>`${Math.min(3,s.loops)}/3 L · ${s.uniqueVertices}/6 pts`},{label:'Ouro · 4 Loops usando ≤6 pontos',check:s=>s.loops>=4&&s.uniqueVertices<=6,progress:s=>`${Math.min(4,s.loops)}/4 L · ${s.uniqueVertices}/6 pts`}]}];
let currentMap=null,state=null,rivalChallenge=null,soundOn=true,musicOn=true,audioCtx=null,musicTimer=null,masterGain=null,musicGain=null,fxGain=null,musicStep=0,mood=0,currentChord=0,ghostTimers=[];
function clearedCount(){return MAPS.reduce((n,m)=>n+(mapProgress(m.id).medal>=1?1:0),0)}
function unlocked(i){if(i===0)return true;const first=mapProgress('first').medal>=1;if(!first)return false;if(i<=4)return true;const n=clearedCount();if(i<=6)return n>=3;if(i<=8)return n>=5;if(i<=10)return n>=7;return n>=9}
function unlockHint(i){if(i===0)return'';if(!mapProgress('first').medal)return'Complete Primeira trama para abrir o Atlas.';if(i<=4)return'';if(i<=6)return`Complete 3 mapas do Atlas · ${clearedCount()}/3`;if(i<=8)return`Complete 5 mapas do Atlas · ${clearedCount()}/5`;if(i<=10)return`Complete 7 mapas do Atlas · ${clearedCount()}/7`;return`Complete 9 mapas do Atlas · ${clearedCount()}/9`}
function mapProgress(id){const map=MAPS.find(m=>m.id===id),version=map?.version||1,p=profile.maps[id];if(p&&(p.version==null||p.version===version)){if(p.version==null)p.version=version;if(p.feat==null)p.feat=false;return p}return{version,medal:0,best:0,attempts:[],feat:false}}
function showAtlas(){const medalTotal=MAPS.reduce((s,m)=>s+mapProgress(m.id).medal,0),goldTotal=MAPS.reduce((s,m)=>s+(mapProgress(m.id).medal>=3?1:0),0),featTotal=MAPS.reduce((s,m)=>s+(mapProgress(m.id).feat?1:0),0),pct=Math.round((medalTotal+featTotal)/(MAPS.length*4)*100);modalWrap.classList.remove('hidden');modal.innerHTML=`<h2>Atlas</h2><p>Cada mapa é um problema geométrico fixo. Vença, volte e complete Prata e Ouro. Sua melhor pontuação fica registrada separadamente para ranking.</p><div class="atlas-progress"><div><b>${medalTotal}/${MAPS.length*3}</b><span>medalhas</span></div><div><b>${goldTotal}/${MAPS.length}</b><span>Ouros</span></div><div><b>${featTotal}/${MAPS.length}</b><span>Feitos</span></div><div><b>${pct}%</b><span>domínio</span></div></div><div class="atlas-grid">${MAPS.map((m,i)=>{const p=mapProgress(m.id),lock=!unlocked(i);return `<button class="map-card ${lock?'locked':''}" ${lock?'disabled':''} data-map="${m.id}"><div class="map-top"><b>${i+1}. ${m.name}</b><div class="medals"><span class="medal ${p.medal>=1?'on':''}">●</span><span class="medal ${p.medal>=2?'on':''}">●</span><span class="medal ${p.medal>=3?'on':''}">●</span><span class="feat-medal ${p.feat?'on':''}" title="${m.feat.label}">◆</span></div></div><small>${lock?unlockHint(i):m.desc}</small><div class="map-goals"><span>${m.goals[0].label}</span><span>${m.goals[1].label}</span><span>${m.goals[2].label}</span><span class="feat-line">◆ ${m.feat.label}</span></div><div class="map-best">Melhor score: ${p.best?fmt(p.best):'—'}${p.bestObjectiveDisplay!=null?` · Melhor ${rankData(m,{}).label}: ${p.bestObjectiveDisplay}`:''}</div></button>`}).join('')}</div><div class="modal-actions"><button class="btn" id="importRoute">Importar rota</button></div>`;modal.querySelectorAll('[data-map]').forEach(b=>b.addEventListener('click',()=>startMap(b.dataset.map)));$('#importRoute').onclick=showImportRoute}
function startMap(id,keepRival=false){clearGhost();if(!keepRival)rivalChallenge=null;currentMap=MAPS.find(m=>m.id===id);state={score:0,crosses:0,echoes:0,loops:0,cleanLoops:0,centerLoops:0,maxVertices:0,triangleLoops:0,symPairs:0,rituals:0,ritualStage:0,uniqueVertices:0,moves:0,current:null,path:[],edges:[],loopsData:[],junctions:[],pts:currentMap.pts.map((p,i)=>({id:i,x:p[0],y:p[1]})),ended:false,goalSeen:[false,false,false]};modalWrap.classList.add('hidden');hint.classList.remove('hide');hint.textContent=currentMap.id==='first'?'Toque em qualquer ponto para começar.':currentMap.goals[0].label;drawGrid();mood=.08;render()}
function fmt(n){return Math.round(n).toLocaleString('pt-BR')} function edgeKey(a,b){return a<b?`${a}-${b}`:`${b}-${a}`} function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)} function area(poly){let s=0;for(let i=0;i<poly.length;i++){const p=poly[i],q=poly[(i+1)%poly.length];s+=p.x*q.y-q.x*p.y}return Math.abs(s/2)}
function intersect(a,b,c,d){const den=(a.x-b.x)*(c.y-d.y)-(a.y-b.y)*(c.x-d.x);if(Math.abs(den)<1e-8)return null;const t=((a.x-c.x)*(c.y-d.y)-(a.y-c.y)*(c.x-d.x))/den,u=-((a.x-b.x)*(a.y-c.y)-(a.y-b.y)*(a.x-c.x))/den;if(t>.02&&t<.98&&u>.02&&u<.98)return{x:a.x+t*(b.x-a.x),y:a.y+t*(b.y-a.y)};return null}
function pointInPoly(pt,poly){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const xi=poly[i].x,yi=poly[i].y,xj=poly[j].x,yj=poly[j].y,hit=((yi>pt.y)!==(yj>pt.y))&&(pt.x<(xj-xi)*(pt.y-yi)/(yj-yi+1e-9)+xi);if(hit)inside=!inside}return inside}
function svg(tag,a){const e=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(a).forEach(([k,v])=>e.setAttribute(k,v));return e}
function drawGrid(){const g=$('#grid');g.innerHTML='';[160,270,360].forEach(r=>g.appendChild(svg('circle',{cx:500,cy:500,r,class:'grid-ring'})));[0,45,90,135].forEach(a=>{const x=Math.cos(a*Math.PI/180)*360,y=Math.sin(a*Math.PI/180)*360;g.appendChild(svg('line',{x1:500-x,y1:500-y,x2:500+x,y2:500+y,class:'grid-rays'}))})}
