'use strict';
function initAudio(){if(audioCtx)return;audioCtx=new(window.AudioContext||window.webkitAudioContext)();const comp=audioCtx.createDynamicsCompressor();comp.threshold.value=-20;comp.knee.value=16;comp.ratio.value=3;masterGain=audioCtx.createGain();musicGain=audioCtx.createGain();fxGain=audioCtx.createGain();masterGain.gain.value=.92;musicGain.gain.value=.12;fxGain.gain.value=.22;musicGain.connect(comp);fxGain.connect(comp);comp.connect(masterGain);masterGain.connect(audioCtx.destination)}
function tone(f,d=.1,type='sine',vol=.028,at=0){if(!soundOn||!audioCtx)return;const t=audioCtx.currentTime+at,o=audioCtx.createOscillator(),g=audioCtx.createGain(),filt=audioCtx.createBiquadFilter();o.type=type;o.frequency.setValueAtTime(f,t);filt.type='lowpass';filt.frequency.value=type==='triangle'?1800:2600;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(filt);filt.connect(g);g.connect(fxGain);o.start(t);o.stop(t+d+.03)}
function pad(freq,d=.8,vol=.024,at=0,detune=0){if(!musicOn||!audioCtx)return;const t=audioCtx.currentTime+at,o=audioCtx.createOscillator(),g=audioCtx.createGain(),lp=audioCtx.createBiquadFilter();o.type='triangle';o.frequency.setValueAtTime(freq,t);o.detune.value=detune;lp.type='lowpass';lp.frequency.value=1100;g.gain.setValueAtTime(.0001,t);g.gain.linearRampToValueAtTime(vol,t+.24);g.gain.linearRampToValueAtTime(.0001,t+d);o.connect(lp);lp.connect(g);g.connect(musicGain);o.start(t);o.stop(t+d+.04)}
function pluck(f,d=.12,vol=.012,at=0){if(!musicOn||!audioCtx)return;const t=audioCtx.currentTime+at,o=audioCtx.createOscillator(),g=audioCtx.createGain(),bp=audioCtx.createBiquadFilter();o.type='square';o.frequency.setValueAtTime(f,t);bp.type='bandpass';bp.frequency.value=1400;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+.005);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(bp);bp.connect(g);g.connect(musicGain);o.start(t);o.stop(t+d+.03)}
function chord(big){const root=big?220:260;[1,1.25,1.5,2].forEach((m,i)=>tone(root*m,.2,'sine',big?.05:.036,i*.035));if(big){tone(110,.32,'triangle',.04,0);tone(660,.18,'sine',.025,.11)}} function nudgeMood(v){mood=Math.min(1,mood+v);document.documentElement.style.setProperty('--hueShift',Math.round(mood*24)+'deg')} function ensureMusic(){if(musicTimer||!musicOn||!audioCtx)return;musicLoop();musicTimer=setInterval(musicLoop,900)}
function musicLoop(){if(!musicOn||!audioCtx)return;const chords=[[174,220,262],[196,247,294],[220,277,330],[247,311,370]],ch=chords[currentChord%chords.length],intensity=Math.max(.06,Math.min(1,mood));pad(ch[0],.9,.014+intensity*.016,0,-6);pad(ch[1],.9,.011+intensity*.014,.06,5);pad(ch[2],.9,.010+intensity*.012,.12,-3);if(musicStep%2===0)pluck(ch[musicStep%3]*2,.12,.008+intensity*.008,.04);if(intensity>.5)pluck(ch[(musicStep+1)%3]*1.5,.11,.008+intensity*.008,.46);musicStep++;currentChord=(currentChord+(intensity>.72?1:0))%chords.length;mood=Math.max(.06,mood*.76)}
function stopMusic(){if(musicTimer){clearInterval(musicTimer);musicTimer=null}}
$('#atlasBtn').onclick=()=>{if(finishTimer)return;showAtlas()};$('#restartBtn').onclick=()=>currentMap?startMap(currentMap.id,!!(rivalChallenge&&rivalChallenge.mapId===currentMap.id)):showAtlas();$('#soundBtn').onclick=()=>{soundOn=!soundOn;$('#soundBtn').textContent=soundOn?'♪':'×';$('#soundBtn').setAttribute('aria-pressed',String(soundOn));initAudio();if(audioCtx&&audioCtx.state==='suspended')audioCtx.resume().catch(()=>{});if(soundOn)tone(320,.08,'sine',.018)};$('#musicBtn').onclick=()=>{musicOn=!musicOn;$('#musicBtn').textContent=musicOn?'♫':'×';$('#musicBtn').setAttribute('aria-pressed',String(musicOn));initAudio();if(audioCtx&&audioCtx.state==='suspended')audioCtx.resume().catch(()=>{});if(musicOn)ensureMusic();else stopMusic()};showAtlas();drawGrid();
