'use strict';
function masteryEarned(rd){return state.score>=rd.mastery&&requirementMet(rd)}
function endRound(){const rd=runPlan[state.round];state.ended=true;const passed=state.score>=rd.target&&requirementMet(rd),mastered=masteryEarned(rd),challenge=!!rd.directive&&goalMet(rd.directive);if(passed){Object.keys(runSources).forEach(k=>runSources[k]+=state.sources[k]||0);Object.entries(state.engineHits||{}).forEach(([id,n])=>runEngineHits[id]=(runEngineHits[id]||0)+n)}if(passed&&challenge){runChallenges++;runFocus++;toast('FOCUS +1',true);haptic(14);nudgeMood(.18)}if(mastered){runMasteries++;runReweaves=Math.min(2,runReweaves+1);toast('MAESTRIA',true);haptic(22);nudgeMood(.28)}if(passed){if(state.round===runPlan.length-1)showWin();else showDraft(mastered,challenge)}else showFail()}
function openSheet(){sheetOverlay.classList.remove('hidden')}function closeSheet(){sheetOverlay.classList.add('hidden')}

function showDraft(mastered=false,challenge=false){
  const nextRound=runPlan[state.round+1];
  let choiceCount=3,choices=buildDraftChoices(nextRound,draftNonce++,choiceCount);
  const renderDraft=()=>{
    const buildTags=[...new Set(state.build.flatMap(id=>knotDefs[id].tags||[]))].slice(0,5);
    const sourceNames={loop:'Loops',cross:'Crosses',echo:'Echoes',line:'Traços'};
    const roundSources=Object.entries(state.sources).sort((a,b)=>b[1]-a[1]);
    const roundTotal=roundSources.reduce((sum,x)=>sum+x[1],0)||1;
    const roundRead=roundSources.filter(x=>x[1]>0).slice(0,2).map(([k,v])=>`${sourceNames[k]} ${Math.round(v/roundTotal*100)}%`).join(' · ')||'Sem engine dominante';const engineRead=Object.entries(state.engineHits||{}).filter(([,n])=>n>0).map(([id,n])=>`${SYNERGY_DEFS[id].name} ×${n}`).join(' · ');
    const passRule=nextRound.requirement?`${fmt(nextRound.target)} + ${goalLabel(nextRound.requirement)}`:fmt(nextRound.target);
    const optional=nextRound.directive?goalLabel(nextRound.directive):'—';
    sheet.innerHTML=`<div class="sheet-copy"><div class="drawer-title">Rodada superada${mastered?' · MAESTRIA':''}${challenge?' · DESAFIO':''}</div><h2>Escolha como sua geometria vai escalar.</h2><p>Knots não são bônus genéricos: eles mudam quais formas valem a pena. Nenhuma escolha específica é obrigatória para passar; a build muda sua margem e sua chance de Maestria. A próxima rodada já está revelada para você decidir com contexto.</p><div class="draft-meta"><span class="draft-tag">Próxima: <b>${nextRound.title}</b></span><span class="draft-tag">Passar: ${passRule}</span><span class="draft-tag">Desafio: ${optional}</span><span class="draft-tag">Reweave: ${runReweaves}</span><span class="draft-tag">Focus: ${runFocus}</span><span class="draft-tag">Leitura: ${roundRead}</span>${engineRead?`<span class="draft-tag engine-read">Engines: ${engineRead}</span>`:''}${buildTags.length?`<span class="draft-tag">Build: ${buildTags.join(' · ')}</span>`:''}</div><div class="sheet-actions">${runReweaves>0?'<button class="btn" type="button" id="reweave">Reweave as opções</button>':''}${runFocus>0&&choiceCount===3?'<button class="btn" type="button" id="focusBtn">Usar Focus: abrir 4ª opção</button>':''}<span class="draft-required">Escolha 1 Knot para continuar</span></div></div><div class="sheet-grid">${choices.map(id=>{const k=knotDefs[id],a=affinityScore(id,nextRound),lab=affinityLabel(a),completed=synergiesCompletedBy(id,state.build);const allies=state.build.filter(other=>(knotDefs[other].tags||[]).some(t=>(k.tags||[]).includes(t))).slice(0,2).map(other=>knotDefs[other].name);const recipe=completed[0];const synergy=recipe?`FECHA ${recipe.name} · ${recipe.desc}`:(allies.length?`Combina com ${allies.join(' + ')}`:'Abre uma linha nova');return`<button class="sheet-choice ${recipe?'synergy-ready':''}" type="button" data-knot="${id}"><span class="sym">${k.symbol}</span><b>${k.name}</b><small>${k.school} · ${k.desc}</small><span class="affinity ${lab[1]}">${lab[0]} com ${nextRound.title}</span><span class="choice-synergy">${synergy}</span></button>`}).join('')}</div>`;
    openSheet();const rw=$('#reweave');if(rw)rw.onclick=()=>{runReweaves--;choices=buildDraftChoices(nextRound,draftNonce++,choiceCount);renderDraft()};const fb=$('#focusBtn');if(fb)fb.onclick=()=>{runFocus--;choiceCount=4;choices=buildDraftChoices(nextRound,draftNonce++,choiceCount);renderDraft()};sheet.querySelectorAll('[data-knot]').forEach(b=>b.addEventListener('click',()=>{const completed=synergiesCompletedBy(b.dataset.knot,state.build),build=state.build.concat([b.dataset.knot]);state=freshState(state.round+1,build);closeSheet();hint.classList.remove('hide');hint.textContent=completed.length?`${completed[0].name} online · ${completed[0].desc}`:(nextRound.requirement?`${nextRound.title}: além da pontuação, cumpra ${goalLabel(nextRound.requirement)}.`:`${nextRound.title}: sua execução decide a forma; sua build decide como ela escala.`);render();if(completed.length){setTimeout(()=>{toast(`ENGINE · ${completed[0].name}`,true);chord(true);haptic(22)},100);nudgeMood(.38)}else nudgeMood(.2)}));
  };renderDraft();
}

function showFail(){const rd=runPlan[state.round],sourceNames={loop:'Loops',cross:'Crosses',echo:'Echoes',line:'Traços'},top=Object.entries(state.sources).sort((a,b)=>b[1]-a[1])[0],read=top&&top[1]>0?` Seu maior motor nesta tentativa foi ${sourceNames[top[0]]} (${fmt(top[1])} pts).`:'' ,active=activeSynergies(state.build),hits=Object.values(state.engineHits||{}).reduce((a,b)=>a+b,0),engineNote=active.length&&!hits?` Sua engine ${active.map(e=>e.name).join(' / ')} estava montada, mas não disparou nesta tentativa.`:'',scoreOk=state.score>=rd.target,reqOk=requirementMet(rd),reason=scoreOk&&!reqOk?`Você bateu a pontuação, mas faltou a condição geométrica obrigatória: ${goalLabel(rd.requirement)}.`:`Você ficou abaixo do alvo de ${fmt(rd.target)}. Existe ao menos uma rota de passagem mesmo sem um Knot específico; tente outra leitura da geometria e use a build para ampliar sua margem.${read}${engineNote}`;sheet.innerHTML=`<div class="sheet-copy"><div class="drawer-title">A trama não fechou</div><h2>${fmt(state.score)} / ${fmt(rd.target)}</h2><p>${reason}</p><div class="sheet-actions"><button class="btn strong" id="retry">Repetir rodada</button><button class="btn" id="newrun">Nova run</button></div></div><div class="sheet-grid"><div class="sheet-choice" style="cursor:default"><span class="sym">◌</span><b>Prepare</b><small>Nem toda forma precisa fechar cedo. Uma linha solta pode abrir a jogada que faltava.</small></div><div class="sheet-choice" style="cursor:default"><span class="sym">✕</span><b>Priorize</b><small>Às vezes cumprir a condição obrigatória cedo libera o restante dos movimentos para pontuar.</small></div><div class="sheet-choice" style="cursor:default"><span class="sym">◇</span><b>Escolha o risco</b><small>O Desafio opcional dá Focus, mas não vale sacrificar a passagem se sua build ainda não sustenta isso.</small></div></div>`;openSheet();$('#retry').onclick=()=>{state=freshState(state.round,state.build);closeSheet();hint.classList.remove('hide');render()};$('#newrun').onclick=()=>startRun()}
function showWin(){const sourceNames={loop:'Loops',cross:'Crosses',echo:'Echoes',line:'Traços'},topSource=Object.entries(runSources).sort((a,b)=>b[1]-a[1])[0],engines=activeSynergies(state.build),engineUse=Object.entries(runEngineHits).filter(([,n])=>n>0).map(([id,n])=>`${SYNERGY_DEFS[id].name} ×${n}`).join(' · ');toast('MASTER KNOT',true);for(let i=0;i<5;i++)setTimeout(()=>burst(500,500,22,true),i*120);[220,277,330,440,554].forEach((f,i)=>tone(f,.45,'sine',.045,i*.06));nudgeMood(.6);sheet.innerHTML=`<div class="sheet-copy"><div class="drawer-title">Run ${runSeed} completa</div><h2>Você construiu uma linguagem.</h2><p>Chegou ao fim das ${runPlan.length} rodadas com ${state.build.length} Knots ativos, ${runMasteries} Maestrias e ${runChallenges} Desafios concluídos. A run agora mede três coisas: geometria, build e capacidade de adaptar seus objetivos. Seu principal motor foi <b>${sourceNames[topSource[0]]}</b>, com ${fmt(topSource[1])} pontos atribuídos.${engines.length?` Engines fechadas: <b>${engines.map(e=>e.name).join(' · ')}</b>.${engineUse?` Ativações: <b>${engineUse}</b>.`:''}`:''}</p><div class="sheet-actions"><button class="btn strong" id="again">Nova run</button></div></div><div class="sheet-grid"><div class="sheet-choice" style="cursor:default"><span class="sym">✦</span><b>Maestrias</b><small>${runMasteries} rodadas acima do alvo alto.</small></div><div class="sheet-choice" style="cursor:default"><span class="sym">◎</span><b>Desafios</b><small>${runChallenges} objetivos opcionais concluídos.</small></div><div class="sheet-choice" style="cursor:default"><span class="sym">⌘</span><b>Knots</b><small>${state.build.length} modificadores na build final.</small></div></div>`;openSheet();$('#again').onclick=()=>startRun()}
function startRun(seed){if(roundEndTimer){clearTimeout(roundEndTimer);roundEndTimer=null}runSeed=Number.isInteger(seed)?seed:Math.floor(1000+Math.random()*9000);runPlan=buildRun(runSeed);history.replaceState(null,'',location.pathname+'?seed='+runSeed);runReweaves=1;runFocus=0;runMasteries=0;runChallenges=0;draftNonce=0;runSources={loop:0,cross:0,echo:0,line:0};runEngineHits={};state=freshState(0,[]);closeSheet();hint.classList.remove('hide');hint.textContent='Toque em qualquer ponto para começar.';drawGrid();render();nudgeMood(0);document.documentElement.style.setProperty('--hueShift','0deg')}
$('#restartBtn').addEventListener('click',()=>startRun());$('#soundBtn').addEventListener('click',()=>{soundOn=!soundOn;$('#soundBtn').setAttribute('aria-pressed',String(soundOn));$('#soundBtn').textContent=soundOn?'♪':'×';initAudio();if(audioCtx&&audioCtx.state==='suspended')audioCtx.resume().catch(()=>{});if(soundOn)tone(320,.08,'sine',.02)});$('#musicBtn').addEventListener('click',()=>{musicOn=!musicOn;$('#musicBtn').setAttribute('aria-pressed',String(musicOn));$('#musicBtn').textContent=musicOn?'♫':'×';initAudio();if(audioCtx&&audioCtx.state==='suspended')audioCtx.resume().catch(()=>{});if(musicOn)ensureMusic();else stopMusic()});$('#infoBtn').addEventListener('click',()=>{const open=drawer.classList.toggle('open');$('#infoBtn').setAttribute('aria-expanded',String(open));$('#drawerState').textContent=open?'fechar':'abrir'});$('#drawerToggle').addEventListener('click',()=>{const open=drawer.classList.toggle('open');$('#infoBtn').setAttribute('aria-expanded',String(open));$('#drawerState').textContent=open?'fechar':'abrir'});$('#ruleTitle').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);toast('SEED COPIADA',false);tone(520,.08,'sine',.02)}catch(e){toast('RUN '+runSeed,false)}});$('#ruleTitle').title='Toque para copiar esta seed';sheetOverlay.addEventListener('click',e=>{if(e.target.classList.contains('sheet-backdrop')&&!state?.ended)closeSheet()});const qs=Number(new URLSearchParams(location.search).get('seed'));startRun(Number.isInteger(qs)&&qs>0?qs:undefined);
